version: '2'

volumes:
  gems:
    driver: local
  data:
    driver: local

services:
  web:
    build: .
    command: bundle exec foreman start web
    volumes:
      - data:/app/db/data
    ports:
      - 80:3000
  worker:
    build: .
    command: bundle exec foreman start worker
    volumes:
      - data:/app/db/data
  redis:
    image: redis
